### ISSUE TITLE
GUI vrstva aplikace

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#14]
Vytvoření základního GUI se všemi potřebnými okny

**Comment by robodasha** [comment]
## Nezapomenout na:
- multi-select (vybirani vic radku pres ctrl/shift)
- moznost mazani kose/archivu po vypnuti aplikace (?) -- nastavitelne
- **DONE** okno na nastaveni prihlasovacich udaju do Google/Facebooku

**Comment by Pitel** [comment]
Zaviram, zaklad GUI je hotov, pro ruzne nedodelaky delejme specialni issues.
