### ISSUE TITLE
Unit testy

### ISSUE THREAD

**Issue by Pitel** [Pitel/GJAddr#19]
- Očekává se použití unit testů.
- Za netriviální funkční testy lze získat zpět body ztracené jinde. Pro funkční testy lze použít např. [fest](http://code.google.com/p/fest) pro Swing či [Selenium](http://seleniumhq.org) pro webové aplikace

Užitečné linky:
- [JUnit](http://www.junit.org)
- [JUnit na Wikipedii](http://en.wikipedia.org/wiki/JUnit) (je tam kostra)
- [JUnit Tutorial](http://www.vogella.de/articles/JUnit/article.html)

Testy (včetně JUnit jaru) by měly být oddělené od kódu!

**Comment by ragaj** [comment]
Persistance layer - DONE

**Comment by robodasha** [comment]
## What is done
- Persistance (Authorization tokens)
- Import/Export (vCard) DONE
- Should I also create test for CSV Import/Export?
- GUI Unit tests (maybe Selenium?)

**Comment by robodasha** [comment]
### Import/Export -- DONE

**Comment by Pitel** [comment]
Selenium umi jen webisky, na Swing vyzkouset [UISpec4J](http://www.uispec4j.org).

**Comment by robodasha** [comment]
Podle zadani: "Pro funkční testy lze použít např. fest pro Swing"

**Comment by ragaj** [comment]
Jelikoz se blizi zkouska, tak nedam veskery effort do ukolu, ktery mel udelat nekdo jiny na ukor spatneho vysledku ze zkousky. 

Sorry, ale uz na to nemam cas.
