### ISSUE TITLE
Import / Export do .gja

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#21]
Přídání možnosti importu/exportu do vlastního formátu, které používáme pro uložení dat. 

Cíl: Rozšíření možnosti importu/exportu, přenositelnost dat mezi našimi aplikacemi.

**Comment by robodasha** [comment]
Import/export obsluhuji tridy ImportWindow a ExportWindow. Obe tridy jsou pripravene pro doplneni importu/exportu naseho formatu.
