### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#23]
Podle RFC 6350 obecne existuji dva zakladni typy: **work** a **home**. Obecne jeden atribut muze mit vic typu
(TEL;TYPE="voice,home":tel:+1-555-555-5555;ext=5555). 

Jednotlive atributy pak muzou mit (krome work a home) dalsi vlastni typy, pritom preddefinovane jsou:
1. **adresa:** pouze work a home
2. **telefon:** text, voice, fax, cell, video, pager, textphone
3. **email:** work a home
4. **messenger:** tam to neni nijak preddefinovane, typ muze byt celkem cokoliv (vypada to treba takhle: IMPP;PREF=1:xmpp:alice@example.com), takze u messengeru by typ mohl byt mit typu retezcovy label
5. **url:** asi jen ty dva zakladni typy, ale vetsinou jsem tam nenasla typ ale jen nejaky label, takze to muzeme udelat asi stejne jako u messengeru

**Comment by ragaj** [comment]
pouze WORK a HOME
