### ISSUE TITLE
XML persistance layer

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#26]
Should we allow import/export of XML files? From the project assignment:
- Uložení kontaktů do standardního formátu (např. XML, SQL databáze, nebo RDF)
- Import kontaktů z nějaké webové/internetové služby (např. Facebook, Gmail, XMPP vCard, ...)
  Currently we work with several different formats so maybe supporting XML format is not necessary.

**Comment by ragaj** [comment]
- XML persistance - DONE
- přepínání v Settings  - DONE
- ukládní fotografie pro XML - TODO
