### ISSUE TITLE
Svatky + Vyroci

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#27]
Add name day notifications and anniversary notifications. There should be same settings as for birthday notifications. On the name day/anniversary day display icon next to contact name.

**Comment by ragaj** [comment]
Citace ze zadani "Upozornění na nadcházející narozeniny/výročí"
-> jak by to bylo pracne udelat? ve vysledku by bylo narozeniny, svatky, vyroci

**Comment by robodasha** [comment]
Tim padem by se asi ke kontaktu musela pridat polozka vyroci nebo by se ruzna data oddelila do separatni tabulky a kazde datum by melo typ (narozeniny/vyroci/svatek) -> tohle se mi asi zda jako lepsi moznost. Pracne to snad moc nebude. Pritom svatek by se automaticky ukladal pri vytvareni kontaktu. Co vy na to? Mam to oddelit do separatni tabulky?

**Comment by ragaj** [comment]
Videl bych to tak, ze kontakt bude mit nove atribut List<Event>, kde event bude obsahovat datum + typ (svatek, narozeniny, vyroci). Takze kazdy kontakt bude mit defaultne pri vytvareni alespon jednu polozku v tom seznamu, a to datum svatku.
- upozorneni tak bude mozne nove nastavit/vypnout zvlast pro narozeniny/svatek/vyroci nebo dohromady pro vsechny tri typy
- kazdy typ udalosti bude mit vlastni ikonku zobrazovanou u jmena v detailu

souhlasite?

**Comment by robodasha** [comment]
Souhlas, presne tak jsem to myslela.
