### ISSUE TITLE
Import -- fotografie

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#31]
Waiting for #6 to be finished.

**Comment by Pitel** [comment]
#6 je hotovo! Fotka je jako `ImageIcon` u `Contact`u.

**Comment by robodasha** [comment]
Should we import bigger pictures from Facebook?
Now we import this: http://graph.facebook.com/damirah/picture
And we could import this: http://graph.facebook.com/damirah/picture?type=large
