### ISSUE TITLE
Sjednoceni designu oken

### ISSUE THREAD

**Issue by Pitel** [Pitel/GJAddr#38]
- Marginy/paddingy
- Ikony

Marginy brat podle importu exportu.

Tyka se to oken pro pridani/upravu kontaktu a spravu skupin.

**Comment by Pitel** [comment]
Kde presne vam to ted vadi? Ja na to nemam nejak cit. U toho okna s prirazenim kotaktu do skupiny a skupiny ke kontaktu se mi naopak libi, ze je to tak "nalepene" na sebe. Dela to proste dojem popupu, kde by se vlocek nemel moc zdrzovat.

**Comment by robodasha** [comment]
Ahoj, co se tyka toho designu oken, mozna bys mohl zkusit upravit zarovnani a sirku panelu s detailem kontaktu. Tady jsem nahrala screenshot: https://github.com/Pitel/GJAddr/blob/master/doc/address.png (omlouvam se, ze je to zrovna v doc/, ale nejak jsem nevedela, kam to soupnout, az na to kouknete, tak to muzu smazat). Nelibi se mi v tom screenshotu chybejici mezera mezi titulkem Address: a tou adresou. Stava se to docela casto. Asi bych dala vetsi minimalni sirku toho panelu a udelala to tak, aby se to nehybalo (tedka se ten vnitrek ruzne posouva podle toho, jaky je tam text). Taky bych tam dala vsechny policka (birthday, note, nickname, ...) i kdyz jsou prazdna. Proste tak, aby se nic nemenilo pri prepinani mezi kontakty. Pokud neni mapa, tak bych tam dala misto toho prazdny obrazek, treba preskrtnuty nebo tak. Ikonce bych odstranila ramecek a vyhradila pro ni nejake presne dane misto, pokud je obrazek mensi, tak se da doprostred a pokud vetsi, tak se treba orizne.

**Comment by robodasha** [comment]
Proste a jednoduse, myslim, ze by to vypadalo nejlip, kdyby tam bylo vsechno pekne na pevno a s predem danou velikosti aby se pri prepinani mezi kontakty to okno samotne vubec nemenilo a menil se jen text.

**Comment by Pitel** [comment]
Mezery za dvojtecky jsem pridal.

S JLabelama je ten problem, ze nezalamujou texty. Takze kdyz ma nekdo dlouhou adresu, tak to proste rpetece a nenadelas nic.

O skryvani policek jsme se o vikendu bavili s Radkem, a shodli jsme se na tom, ze je chceme skryvat kdyz jsou prazdne.

Jak neni mapa? Ta mapa je tam snad vzdycky, kdyz je vyplnena adresa (kdyz jsou v ni nesmysly, tak i ta mapa ukazuje nekam divne, ale to detekovat nedokazeme). Problem s mapou spis je, ze pri jejim nacitani se zasekne UI. Jak slozity je to nacitani pustit ve vlakne?

Fotce bych ramecek nechal, at je zrejmy ze na ni jde kliknout. Krom toho, fotky se bezne davaj do ramecku.

**Comment by robodasha** [comment]
OKA, co to udelat tak, jako v tomhle screenshotu? https://github.com/Pitel/GJAddr/blob/master/doc/example.png

Labely jsou zarovnane doprava a srovnane s ikonkou. Texty zarovnane doleva a pokud jsou delsi, tak jsou ukoncene teckami.

Pokud jste se shodli, ze prazdna policka by se mela skryvat, tak fajn, to jsem nevedela.

Co se tyka mapky myslela jsem to v pripade, ze by jsme meli vsechna policka zobrazena i kdyz jsou prazdna -> v tom pripade by se tam dala i prazdna mapka. Pokud jste se shodli na skryvani prazdnych policek, tak je tohle nerelevantni.

Pokud bys delal nacitani mapky ve vlakne, tak je to rekla bych otazka chvilky (aspon me prekvapilo, jak rychle a jednoduse slo napsat to vlakno pro import).

Ramecek bych tedy nechala, ale mozna bych ho zmenila na nejaky hezkci (treba jako v tom screenshotu, tak jak to vypada ted -- jako button -- je to trochu divne, mi prijde). Ikonku smajlika bych asi taky za neco vymenila (ne ze bych mela neco proti smajlikovi :), ale zda se mi, ze pochopitelnejsi bude mit prazdnou siluetu, jako treba na Facebooku: http://www.endlesssimmer.com/wp-content/uploads/2010/05/facebook-no-image1.gif)

**Comment by robodasha** [comment]
Ahoj, potrebovala bych pomoct.
Resila jsem ted ten panel s detailem kontaktu a podarilo se mi to asi trochu vylepsit, screenshot idealniho pripadu je tady: https://github.com/Pitel/GJAddr/blob/master/doc/current.png
Mam s tim ale 2 problemy:
1. Jak vidite, tak se ted zalamuje adresa. Je to diky tomu, ze je vlozena do HTML, ale bohuzel taky diky tomu, ze to cele okno NENI vlozene do scroll panel. Tim padem okno nejde scrollovat. Jakmile ho vlozim do scroll pane, tak se adresa uz nezalomi, i kdyz nastavim horizontal scroll na zakazany a povolim pouze vertical. Takze ted nevim co s tim.
2. (Tohle jsem uz OPRAVILA) Zjistila jsem, ze kdyz nektere polozky v detailu chybi, tak se vytvori mezi temi zobrazenymi vetsi vertikalni mezera, viz screenshot: https://github.com/Pitel/GJAddr/blob/master/doc/wrong.png. Opet bohuzel nevim co s tim.
Honzo, neporadis?

**Comment by robodasha** [comment]
Bod cislo 2 predchoziho komentare ignorujte, prave jsem ho opravila :)

**Comment by robodasha** [comment]
Okna zminena v predchozim commitu jsou ted modalni. Zdalo se mi to lepsi, nez tam davat semafor. Zatim jsem zmenila jen tato okna pro pripad, ze by jste s tim nesouhlasili. 
P.S: Zavirani okna pomoci ESC jsem tim padem musela prepsat -- viz treba AboutWindow.

**Comment by Pitel** [comment]
No ja neved ani o tom triku s `<html>`... a co jsem ted googlil, tak to vypada na nejakou bugu v `JScrollPane`. :(

**Comment by robodasha** [comment]
OK, kazdopadne diky. Budu to zkouset :P
Jinak, co si tedy myslite o tech modalnich oknech? Mam udelat vsude?

**Comment by Pitel** [comment]
Urcite jo. Vsak to bylo i cilem aby ty okna byly modalni, pokud se nepletu.

**Comment by ragaj** [comment]
Modalni okna - navhoval jsem to, ale na konferenci jste mi rekli, ze se Vam to libi tak jak je => SOUHLASIM s modalnimi

Honzo podivej se na ten scrollbar u detailu a pomoz pls Drazi s nim.

**Comment by ragaj** [comment]
jen dodam, ze bych udelal modalni uplne vsechna okna v aplikaci, treba import/export/preferences/... to aktualne nemaji.
