### ISSUE TITLE
Připomínky narozenin, výročí

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#4]
automatické upomínky blížicích se narozenin 
??? daemon či při spuštění

**Comment by robodasha** [comment]
Po spusteni aplikace zobrazit okno se seznamem narozenin a vyroci behem nasledujiciho tydne a podobne.
Vedle kontaktu ikonka s dortikem nebo neco na ten zpusob.

**Comment by robodasha** [comment]
## What is done:
- after app starts a window with birthday notifications is displayed (birthday "to happen" within one month)
- contact with birthday within one month has a different icon next to his name (details window) -- we should discuss when to display this icon (one month in advance, one week in advance, only on the day of bday, or change this icon during the time?)

**Comment by robodasha** [comment]
## What is currently missing:
- icon in the main contacts table
- functionality behind "Don't show anymore" button in NotificationsWindow (if we decide to keep this button -- to be discussed)

**Comment by robodasha** [comment]
Ticket is done apart of functionality to display icons in the main contacts window. This part won't be done. (The way I understand is that I would have to rewrite the table renderer, which would likely take too much time. Maybe this could be done in the end of development as an extension.)
