### ISSUE TITLE
Sjednotit klavesove zkratky

### ISSUE THREAD

**Issue by Pitel** [Pitel/GJAddr#40]
Zapomneli jsme probrat po Skypu. Co si pamatuju, tak jediny konflikt byl `Ctrl` + `E`, ktery ma jak Export, tak Editace.

Zamerne jsem nikoho nepriradil, protoze je to k diskuzi.

**Comment by ragaj** [comment]
Zkontroluj prosim take funkcnost vsech pouzivanych klavesovych zkratek. CTRL + E bych ponechal spise pro editaci, pro import bych pouzil treba ALT + E, export bych take s ALT...

**Comment by robodasha** [comment]
Budeme mit nekde dostupnou dokumentaci, kde bude seznam klavesovych zkratek? Predpokladam, ze to prijde treba sem: http://pitel.github.com/GJAddr/
Behem toho sjednocovani by to mozna chtelo sepsat.

**Comment by Pitel** [comment]
Taky si říkám, že asi není nutný mít klávesovou zkratku pro mazání, páč to stejně dělá klávesa Delete.

**Comment by ragaj** [comment]
@Pitel: +1

**Comment by Pitel** [comment]
Sepsal jsem zkratky do [wiki](https://github.com/Pitel/GJAddr/wiki/Kl%C3%A1vesov%C3%A9-zkratky).

Btw, ty zkratky pro kontakty a skupiny (v podstate vsechny ktere jsou v popup menu) mi nefunguji! Muzes se na to Radku podivat?

**Comment by ragaj** [comment]
podivam se na to ;-)
