### ISSUE TITLE
Contact detail - groups membership

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#41]
Use following method from the DB
-  public List<Group> getAllGroupsForContact(Contact contact);

Hint: It possible to show like a string, delimited with commas.

**Comment by Pitel** [comment]
Jak dostat ten hezky String se seznamem skupin? Kdyz nad tim listem zavolam `.toString()`, tak dostanu `[Derps (2), Herps (4)]`. Mame na to nejakou metodu, nebo to musim prohnat nejakym regexpem?

**Comment by ragaj** [comment]
nemam na to metodu, ale neni problem napsat, pokud potrebujeme

**Comment by Pitel** [comment]
Napsat si sám.
