### ISSUE TITLE
Nefunguje ukladani nebo ziskavani udalosti

### ISSUE THREAD

**Issue by Pitel** [Pitel/GJAddr#50]
Pres `contact.setBirthday(datum)` nastavim narozeniny, nasledny `contact.getBirthday()` vrati `null` (nebo mozna ne primo `null`, ale proste v tom eventu neni zadne datum).

**Comment by robodasha** [comment]
Tohle byla moje chyba a uz jsem to opravila, za chvili to commitnu.
