### ISSUE TITLE
Nekorektni zobrazeni prazdnych polozek kontaktu

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#51]
Pokud vytvorim kontakt pouze se jmenem a prijmenim, tak v hlavni tabulce s kontakty se u emailu a telefonu zobrazi dve carky takto: ", , "

**Comment by Pitel** [comment]
S Radkem o tom vime, domluva byla ze se to bude resit na urovni databaze.

**Comment by ragaj** [comment]
mam to v TODO
