### ISSUE TITLE
Export vCard

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#55]
- nefunguje export vCard
- PRETESTOVAT FUNKCNOST VSECH IMPORTU/EXPORTU

**Comment by robodasha** [comment]
Nejak se mi nedari tohle znovu vyvolat.
Jestli ti to stale nefunguje, nepopsal bys sem prosim, co a jak jsi exportoval?

**Comment by ragaj** [comment]
BURNED IN PAST
