### ISSUE TITLE
V detailech okna se nevykresluji ikony udalosti

### ISSUE THREAD

**Issue by Pitel** [Pitel/GJAddr#56]
Je na to kod:

``` java
if (contact.hasBirthday()) { //Podobne pro dalsi typy
    bdayIcon.setVisible(true);
} else {
    bdayIcon.setVisible(false);
}
```

Takze podezriva ze v tom `hasBirthday` je neco spatne.

P. S. Presunu jsem ty ikony o radek niz, ale ani pred tim mi to nefungovalo spravne.

**Comment by robodasha** [comment]
V moji verzi (naposledy pull vcera behem meetingu) to funguje. Radek to vcera ukazoval a taky mu to fungovalo. Jsi si jisty, ze to neni neco u tebe?

**Comment by Pitel** [comment]
Jako vyloucit to nemuzu... ale ted jsem uplne smazal `~/.gjaddr`, spustil to, vytvoril prvni kontakt, nastavil mu narozeniny apod. Vypnul aplikaci, spustil ji znovu. Vyskocilo okno s nadchazejicimi udalostmi, odklikknul jsem ho, vybral kontakt, a ikony nikde. Kdyz ty podminky vykricnikem zneguju, tak tam jsou.

**Comment by robodasha** [comment]
Me to funguje.
Poznamka: ikonky se zobrazuji pouze primo v den te udalosti, ne dopredu.
