### ISSUE TITLE
Messangers support

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#59]
- update import/export - celkově všude kde to má smysl, mimo jiné kód níže
- okno add/edit - možnost editace těchto položek - DONE
- zobrazení v detailu - DONE
- validace - DONE

``` java
//GoogleImport.java - line 111
// get messengers - TODO get messenger type
List<Messenger> messengers = new ArrayList<Messenger>();
for (Im im : entry.getImAddresses()) {
  messengers.add(new Messenger(MessengersEnum.OTHER, im.getAddress()));
}
```

**Comment by Pitel** [comment]
V okne a detailesch uz to od rana je... oh wait, ja to zapomnel pushnout ;D

Ale chce to zas pridato check na prazdny hodnoty.

Validace ICQ a Jabberu by asi davala smysl... ICQ muzem klidne zrecyklovat z telefoniho cisla a jabber z emailu

**Comment by ragaj** [comment]
Validaci a check si beru na starost

**Comment by robodasha** [comment]
Facebook nepodporuje export messengeru a stejne tak vCard (tam to neumi nase knihovna), u Google a CSV to je, takze toto issue zaviram.
