### ISSUE TITLE
Práce s fotografií

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#6]
CRUD akce

**Comment by Pitel** [comment]
Uz to prakticky funguje, diky commitu ed3aaf8. Akorat to vypada, ze si Java ten `ImageIcon` uklada jako pole pixelu bez komprese, takze kazda fotecka ma radove megabajty. Coz neni idelani.

Zkusim to upravi tak, aby se fotka jako takova nakopirovala do `.gjaddr` adresare, pojmenovala se podle `Contact.id`, a pak se odtud nacitala.

**Comment by Pitel** [comment]
Pomoci [`Image.getScaledInstance()`](http://docs.oracle.com/javase/6/docs/api/java/awt/Image.html) resizovat obrazek na neco mensiho, a ten pak pouzit. `ImageIcon` dokaze prijmout `Image` jako konstruktor, coz je win. Do `Contact` pak fotku taky ukladat jako `Image`.

**Comment by Pitel** [comment]
Zkusit zprovoznit upravu fotky i z panelu s detailem.
