### ISSUE TITLE
Preferences window

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#60]
- okno nejde vubec resizovat
- vidim pouze jeden TAB - nebylo by lepsi jich videt vice? takhle to pusobi, ze je to chyba

Nevim, zda je to chyba windows nebo to mate stejne?

Podivej se pls na screenshot: 

https://github.com/Pitel/GJAddr/blob/master/doc/bug_preferences.png

**Comment by robodasha** [comment]
TODO:
- zarovnat obsah vsech tabu doleva **nahoru**
