### ISSUE TITLE
Vytvoreni databaze pro autentizacni tokeny

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#63]
Zjistila jsem, ze kdyz smazu databazove soubory a nahodim znovu data spustenim DatabaseTest.java, tak se vytvori vsechny databazove soubory krome auth.gja. Zkousela jsem ted prijit na to, jak to automaticke vytvoreni udelat a nepodarilo se mi na to prijit. Nepodival by ses na to prosim Radku?
Taky jsem se chtela zeptat, kdy se ty databazove soubory vytvari, pokud neexistuji. Vytvori se pri spusteni aplikace?

**Comment by ragaj** [comment]
Databazove soubory se vytvari pouze tehdy, maji-li smysl. Tzn. Pokud tabulky auth, contacts, ... obsahuji nejaky zaznam. Pokud spustis DatabaseTest.java, tak se vytvori spravne jen ty tri bez Auth, protoze test s nimi nepracuje.

**Comment by ragaj** [comment]
BURNED IN PAST
