### ISSUE TITLE
Vylepseni okna About

### ISSUE THREAD

**Issue by robodasha** [Pitel/GJAddr#65]

**Comment by ragaj** [comment]
Navrhuji pridat:
- titulek okna
- verze programu
- akademicky rok
- Projekt do predmetu Graficka uzivatelska rozhrani
- Fakulta informacnich technologii, VUT Brno

Jeste neco dalsiho?

**Comment by ragaj** [comment]
Zaroven to prosim udelat ve stejnem designu pisma a labelu jako je editace kontaktu (bez tabu).

**Comment by ragaj** [comment]
Issue je prirazeno Honzovi, udelas to nebo to ma udelat nekdo jiny?

**Comment by Pitel** [comment]
Udelam to

**Comment by Pitel** [comment]
Mame nekde nejakou konstantu pro verzi progranu, nebo tam mam proste napsat 1.0?

**Comment by robodasha** [comment]
Myslim, ze co napsal Radek zni dobre. Pridas to tam Honzo?

**Comment by robodasha** [comment]
Omlouvam se za predchozi komentar, neudelala jsem clean&build, takze jsem nevidela zmenu.. Uz jsem nejaka unavena :P
Neslo by to jen nejak rozumne zarovnat?
Nebo jestli jsem uz moc perfekcionisticka, tak me umlcte :)

**Comment by robodasha** [comment]
Dalo by se zarovnat bud vsechno doleva nebo vsechno doprostred?

**Comment by robodasha** [comment]
Super, diky.
