### ISSUE TITLE
Contact detail/add/edit bugs

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#67]
Prilozene PDF obsahuje 7 screenshotu s popisem bugu.

https://github.com/Pitel/GJAddr/blob/master/doc/detail_bugs.pdf

**Comment by Pitel** [comment]
Ale ty ikonky uz jsou zmenseny, viz 7e352dd63bc67f148e221eceeb77d64a2812347c

**Comment by ragaj** [comment]
Omlouvam se ma chyba, nedal jsem clean&build, ale me porad build stare resource soubory.. 

IKONKY - DONE tedy

**Comment by robodasha** [comment]
1. DONE
2. otevira se mi jenom jednou - NOT RELEVANT
3. Zalomeni dlouhe poznamky --> pokud je to jedno slovo jako v tom prikladu, co jsi poslal, tak bude potreba v persistence udelat nejakou metodu getNoteWithLineBreaks a vynutit zalomeni. Protoze HTML zalamuje jen v mezerach. - DONE
4. Tohle jsem psala do #38 -- precti si to prosim. Mam problem s tim, ze jak se tam da scrollbar tak se nic nezalamuje. - DONE
5. u me se neprojevuje - NOT RELEVANT
6. opravim - DONE
7. opravim - DONE

**Comment by ragaj** [comment]
ad 2. u me uz taky ne, tak nevim no
ad 3. provedu zmenu v DB
ad 4. Honzo pomoz prosim Drazi se Scrollbarem
ad 5. Honzo, u Tebe se to projevuje?

**Comment by Pitel** [comment]
Me se to ukazuje dobre:

![Note](http://i.imgur.com/Bbzn8.png)
