### ISSUE TITLE
Odstranit TODO

### ISSUE THREAD

**Issue by ragaj** [Pitel/GJAddr#69]
[AuthToken.java at line 10, column 4]   // TODO:
[CsvImportExportTest.java at line 85, column 12]          // TODO URLs
[FacebookOauth.java at line 20, column 4]   \* TODO: - read application ID from settings file/table
[GJAddrGuiTest.java at line 15, column 27]   \* GUI tests using FEST - TODO
[GoogleImport.java at line 110, column 29]          // get messengers - TODO get messenger type
[GoogleOauth.java at line 17, column 4]   \* TODO: - read settings from settings file/table
[GoogleOauth.java at line 80, column 26]     \* Application secret. TODO HIDE!!!!
[ImportWindow.java at line 22, column 4]   \* TODO - messages in case of errors

**Comment by robodasha** [comment]
Missing just [GJAddrGuiTest.java at line 15, column 27] \* GUI tests using FEST - TODO
But I suppose that won't be done, so I'm closing this issue.
